export const alphabetRUS = [
  [
    { letter: 'й', id: '1', status: 'key' },
    { letter: 'ц', id: '2', status: 'key' },
    { letter: 'у', id: '3', status: 'key' },
    { letter: 'к', id: '4', status: 'key' },
    { letter: 'е', id: '5', status: 'key' },
    { letter: 'н', id: '6', status: 'key' },
    { letter: 'г', id: '7', status: 'key' },
    { letter: 'ш', id: '8', status: 'key' },
    { letter: 'щ', id: '9', status: 'key' },
    { letter: 'з', id: '10', status: 'key' },
    { letter: 'х', id: '11', status: 'key' },
    { letter: 'ъ', id: '12', status: 'key' },
  ],
  [
    { letter: 'ф', id: '13', status: 'key' },
    { letter: 'ы', id: '14', status: 'key' },
    { letter: 'в', id: '15', status: 'key' },
    { letter: 'а', id: '16', status: 'key' },
    { letter: 'п', id: '17', status: 'key' },
    { letter: 'р', id: '18', status: 'key' },
    { letter: 'о', id: '19', status: 'key' },
    { letter: 'л', id: '20', status: 'key' },
    { letter: 'д', id: '21', status: 'key' },
    { letter: 'ж', id: '22', status: 'key' },
    { letter: 'э', id: '23', status: 'key' },
  ],
  [
    { letter: 'я', id: '24', status: 'key' },
    { letter: 'ч', id: '25', status: 'key' },
    { letter: 'с', id: '26', status: 'key' },
    { letter: 'м', id: '27', status: 'key' },
    { letter: 'и', id: '28', status: 'key' },
    { letter: 'т', id: '29', status: 'key' },
    { letter: 'ь', id: '30', status: 'key' },
    { letter: 'б', id: '31', status: 'key' },
    { letter: 'ю', id: '32', status: 'key' },
  ],
];
export const alphabetEN = [
  [
    { letter: 'q', id: '1', status: 'key' },
    { letter: 'w', id: '2', status: 'key' },
    { letter: 'e', id: '3', status: 'key' },
    { letter: 'r', id: '4', status: 'key' },
    { letter: 't', id: '5', status: 'key' },
    { letter: 'y', id: '6', status: 'key' },
    { letter: 'u', id: '7', status: 'key' },
    { letter: 'i', id: '8', status: 'key' },
    { letter: 'o', id: '9', status: 'key' },
    { letter: 'p', id: '10', status: 'key' },
  ],
  [
    { letter: 'a', id: '11', status: 'key' },
    { letter: 's', id: '12', status: 'key' },
    { letter: 'd', id: '13', status: 'key' },
    { letter: 'f', id: '14', status: 'key' },
    { letter: 'g', id: '15', status: 'key' },
    { letter: 'h', id: '16', status: 'key' },
    { letter: 'j', id: '17', status: 'key' },
    { letter: 'k', id: '18', status: 'key' },
    { letter: 'l', id: '19', status: 'key' },
  ],
  [
    { letter: 'z', id: '20', status: 'key' },
    { letter: 'x', id: '21', status: 'key' },
    { letter: 'c', id: '22', status: 'key' },
    { letter: 'v', id: '23', status: 'key' },
    { letter: 'b', id: '24', status: 'key' },
    { letter: 'n', id: '25', status: 'key' },
    { letter: 'm', id: '26', status: 'key' },
  ],
];
